---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ host_server }}"
  - api: "{{ api_key }}"

  tasks:
    #  Gather all Subnet
    - name: Gather Subnet
      b1_ipam_subnet_gather:
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: gather
      register: subnets
    - debug: msg="{{ subnets }}"

    #  Gather Subnet with filters and fields.
    - name: Gather the Subnet detail
      b1_ipam_subnet_gather:
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: gather
        fields: ['id', 'name', 'dhcp_options', 'tags' ]
        filters: {'address': '172.16.0.0'}
      register: subnet
    - debug: msg="{{ subnet }}"

    #  Gather Subnet with multiple filters.
    - name: Gather Subnet with a given tag
      b1_ipam_subnet_gather:
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: gather
        fields: ['id', 'dhcp_options', 'tags' ]
        filters: {'name': 'Test-Ansible-AB_nextAvailable', 'address':'172.16.0.32'}
      register: subnet
    - debug: msg="{{ subnet }}"

