---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ host_server }}"
  - api: "{{ api_key }}"

  tasks:
    #  Gather ID for a given IP space
    - name: Gather IP space
      b1_ipam_ip_space_gather:
        host: "{{ host_server }}"
        api_key: "{{ api }}"
        state: gather
      register: ip_spaces
    - debug: msg="{{ ip_spaces }}"

    #  Gather ID for a given IP space
    - name: Gather the ID information of an for a given name
      b1_ipam_ip_space_gather:
        host: "{{ host_server }}"
        api_key: "{{ api }}"
        state: gather
        fields: ['id' ]
        filters: {'name': 'testIP1'}
      register: ip_spaces_id
    - debug: msg="{{ ip_spaces_id }}"

    #  Gather Tags for a given IP space
    - name: Gather the tags  of an for a given IPSpace name
      b1_ipam_ip_space_gather:
        host: "{{ host_server }}"
        api_key: "{{ api }}"
        state: gather
        fields: ['tags' ]
        filters: {'name': 'testIP1'}
      register: ip_spaces_tags
    - debug: msg="{{ ip_spaces_tags }}"

    #  Gather dhcp options for a given IP space
    - name: Gather the tags  of an for a given IPSpace name
      b1_ipam_ip_space_gather:
        host: "{{ host_server }}"
        api_key: "{{ api }}"
        state: gather
        fields: ['dhcp_options' ]
        filters: {'name': 'testIP1'}
      register: ip_spaces_dhcp_options
    - debug: msg="{{ ip_spaces_dhcp_options }}"

    #  Gather asm config for a given IP space
    - name: Gather the asm config  of an for a given IPSpace name
      b1_ipam_ip_space_gather:
        host: "{{ host_server }}"
        api_key: "{{ api }}"
        state: gather
        fields: ['asm_config' ]
        filters: {'name': 'testIP1'}
      register: ip_spaces_asm_config
    - debug: msg="{{ ip_spaces_asm_config }}"