---

- name: Initializing vars
  debug: msg="gathering view facts"
  vars:
    view_id: []
    
  
- name: Get dns view
  b1_dns_view:
    dns_view_auth_key: "{{ api_key }}"
    name: test
    state: gather
    host: "{{ host_server }}"
  register: result

- name: filter dns view json response
  set_fact: my_dict="{{ item  }}"
  when: item | type_debug == "dict"
  with_items: "{{ result.values() }}"

- name:  Gather view id and name
  set_fact: dns_view_list="{{ item.value | map('json_query','{name:name,id:id}')  }}"
  loop: "{{ my_dict | dict2items}}"


- name: fetch existing id view
  set_fact: view_id="{{ view_id + [(dns_view_list|selectattr('name', 'equalto', item )) | map(attribute='id') | first]}}"
  when: (dns_view_list|selectattr("name", "equalto", item )) 
  with_items: "{{  create_dns_view_list }}"
  vars:
    view_id: []
 
- name: unique view id
  set_fact: view_id="{{ view_id }}"
  when: view_id is defined
