

   - name: Delete content & directory
     file:
      state: absent
      path: "$PWD/server_info.csv"


   - name: filter zone host data
     lineinfile:
       path: "$PWD/server_info.csv"
       line: "'View Name is:  {{ item.view_name  }}, Primary zone is: {{ item.absolute_zone_name }}, Record name is: {{ item.name_in_zone }}, Zone name is: {{ item.absolute_zone_name }}'"
       create: yes
     when: write_file is defined
     with_items: "{{ zone_view_list }}"


   - name: Print zone data
     debug: msg="item"
     when: item.absolute_zone_name == find_zone and find_zone is defined
     with_items: "{{ zone_view_list }}" 

   - name: Print record data
     debug: msg="item"
     when: item.name_in_zone == find_record and find_record is defined
     with_items: "{{ zone_view_list }}" 

   - name: Print View data
     debug: msg="item"
     when: item.name == find_view and find_view is defined 
     with_items: "{{ dns_view_list }}" 

  
