
- name: Get dns primary zone
  b1_dns_zone:
     dns_view_auth_key: "{{ api_key }}"
     state: gather_host
     host: "{{ host_server }}"
  register: zone_result

- name: filter zone host data
  set_fact: zone_dict="{{ item  }}"
  when: item | type_debug == "dict"
  with_items: "{{ zone_result.values() }}"

- name:  zone vhost  dataaaaa
  set_fact: zone_view_list="{{ item.value | map('json_query','{ip_address:ip_address,id:id,display_name:display_name}')  }}"
  loop: "{{ zone_dict | dict2items}}"

- debug: msg="{{ auth_server }}"

- debug:  msg="{{ zone_view_list }}"

- name: fetch host id
  set_fact: host_id="{{ host_id + [(zone_view_list|selectattr('ip_address', 'equalto', item )) | map(attribute='id') | first] }}"
  when: (zone_view_list|selectattr("ip_address", "equalto", item )) and "{{ auth_server|length>0 }}"
  with_items: "{{ auth_server }}"
  vars:
    host_id: []


#- debug: msg="{{ view_id }}"
  
#- debug:  msg="{{ zone_view_list }}"
- debug: msg="{{ host_id }}"
   
