
- name: Delete ptr
  b1_ptr_record:
    dns_view_auth_key: "{{ api_key }}"
    name: "{{ item }}"
    host: "{{ host_server }}"
    state: absent
  with_items: "{{ zone_id_ptr_delete }}"
  when: zone_id_ptr_delete is defined


   
