
- name: Create ptr
  b1_ptr_record:
    name: "{{ item.2 }}"
    ptr_domain_name: "{{ item.1 }}"
    ptr_address: "{{ item.0 }}" 
    type: "PTR"
    dns_view_auth_key: "{{ api_key }}"
    host: "{{ host_server }}"
    state: present
  when: item.2 != None and item.1  != None
  with_together:
    - "{{ ptr_address }}"
    - "{{ ptr_domain_name }}" 
    - "{{ zone_id_ptr }}"
