
- name: Delete cname
  b1_cname_record:
    dns_view_auth_key: "{{ api_key }}"
    name: "{{ item }}"
    host: "{{ host_server }}"
    state: absent
  with_items: "{{ zone_id_cname_delete }}"
  when: zone_id_cname_delete is defined


   
