
 
- name: Create dns view if not present
  b1_dns_view:
     name: "{{ item }}"
     dns_view_auth_key: "{{ api_key }}"
     state: present
     host: "{{ host_server }}"
  when: not (dns_view_list|selectattr("name", "equalto", "{{ item }}")) 
  with_items: "{{  create_dns_view_list|unique }}"

