   
     
- name: Delete zone
  b1_dns_zone:
    dns_view_auth_key: "{{ api_key }}"
    name: "{{ item }}"
    state: absent
    host: "{{ host_server }}"
  with_items: "{{ delete_dns_zone_list }}"
  when: delete_dns_zone_list is defined

- name: Delete dns view
  b1_dns_view:
    name: "{{ item }}"
    dns_view_auth_key: "{{ api_key }}"
    state: absent
    host: "{{ host_server }}"
  when: (dns_view_list|selectattr("id", "equalto", "{{ item }}" ))
  with_items: "{{ view_id|unique }}"
  when: view_id is defined

   
