---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"
  tasks:

    - name: GET all DNS Authoritative Zones
      b1_dns_auth_zone:
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: get

    - name: GET DNS Authoritative Zone
      b1_dns_auth_zone:
        api_key: "{{ api }}"
        host: "{{ host }}"
        view: "Test-View2"
        fqdn: "Test-Zone"
        state: get

    - name: Create DNS Authoritative Zone
      b1_dns_auth_zone:
        fqdn: "Test-Zone"
        view: "Test-View2"
        primary_type: "cloud"
        internal_secondaries: 
          - "{{ On Prem Host Name }}"
        tags:
          - Name: "amit-zone"
        comment: "This is zone"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: present

    - name: Update DNS Authoritative Zone
      b1_dns_auth_zone:
        fqdn: "Test-Zone"
        view: "Test-View2"
        internal_secondaries:
          - "{{ On Prem Host Name }}"
        tags:
          - Name: "amit-zone2"
        comment: "This is an update"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: present

    - name: Delete DNS Authoritative Zone
      b1_dns_auth_zone:
        fqdn: "Test-Zone"
        view: "Test-View2"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: absent
