 
- include: task.yml

- name: Configure dns zone
  hosts: localhost
  collections:
    - infoblox.b1ddi_modules
  roles:
    - { role: b1_get, when get_dns_view is defined }
    - { role: b1_dns_view, when create_dns_view is defined or delete_dns_view is defined }
    - { role: b1_dns_zone, when create_dns_zone is defined or delete_dns_zone is defined }
    - { role: b1_a_record, when create_a_record is defined or delete_a_record is defined }
    - { role: b1_cname_record, when create_cname_record is defined or delete_cname_record is defined }
    - { role: b1_ptr_record, when create_ptr_record is defined or delete_ptr_record is defined }
    - { role: b1_ns_record, when create_ns_record is defined or delete_ns_record is defined }

