
- name: Delete zone
  b1_dns_zone:
    dns_view_auth_key: "{{ api_key }}"
    name: "{{ item }}"
    host: "{{ host_server }}"
    state: absent
  with_items: "{{ delete_dns_zone_list }}"
  when: delete_dns_zone_list is defined


   
