
- name: Delete ns
  b1_ns_record:
    dns_view_auth_key: "{{ api_key }}"
    name: "{{ item }}"
    host: "{{ host_server }}"
    state: absent
  with_items: "{{ zone_id_ns_delete }}"
  when: zone_id_ns_delete is defined


   
