
- name: Create cname
  b1_cname_record:
    name: "{{ item.2 }}"
    cname: "{{ item.1 }}"
    cname_name: "{{ item.0 }}" 
    type: "CNAME"
    dns_view_auth_key: "{{ api_key }}"
    host: "{{ host_server }}"
    state: present
  when: item.2 != None and item.1  != None
  with_together:
    - "{{ cname_name }}"
    - "{{ cname }}" 
    - "{{ zone_id_cname }}"
